### ISSUE TITLE
请发布从源码编译的方法

### ISSUE THREAD

**Issue by yydcool** [tcp-nanqinlang/lkl-rinetd#2]
作者南琴浪你好！
我对bbr和lkl非常好奇，想改动一些lkl的时钟相关代码进一步提高bbr的效率。
我好奇在发布的文件里没有看到liblkl-hijack.so文件。我希望可以学习你编译lkl+rinetd的方法，或者在你发布rinetd环境中开发，但是发布的rinetd只有二进制文件并没有编译过程。请问是否也可以发布rinetd的编译方法？ 谢谢！

**Comment by nanqinlang** [comment]
你好。

如果是要研究 `bbr` 代码的话，建议还是使用 `module compiling` 模式（也就是例如 KVM 环境下的 `tcp_bbr.ko` 的产生过程）
